//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALOS_Web_Admin.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALOS_Web_Admin.Helpers.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You recharge amount is less, it must at least 25 afg.
        /// </summary>
        public static string Operator1AmountMessage {
            get {
                return ResourceManager.GetString("Operator1AmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You recharge amount is less, it must at least 10 afg.
        /// </summary>
        public static string Operator2AmountMessage {
            get {
                return ResourceManager.GetString("Operator2AmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You recharge amount is less, it must at least 10 afg.
        /// </summary>
        public static string Operator3AmountMessage {
            get {
                return ResourceManager.GetString("Operator3AmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You recharge amount is less, it must at least 10 afg.
        /// </summary>
        public static string Operator4AmountMessage {
            get {
                return ResourceManager.GetString("Operator4AmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You recharge amount is less, it must at least 10 afg.
        /// </summary>
        public static string Operator5AmountMessage {
            get {
                return ResourceManager.GetString("Operator5AmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have insuffinet amount in your account.
        /// </summary>
        public static string UserBalanceMessage {
            get {
                return ResourceManager.GetString("UserBalanceMessage", resourceCulture);
            }
        }
    }
}
